@port = 3005
@apiBaseUrl = http://localhost:{{port}}/api
@marvelApiBaseUrl = {{apiBaseUrl}}/marvel
@omdbApiBaseUrl = {{apiBaseUrl}}/omdb
@swApiBaseUrl = {{apiBaseUrl}}/sw

###

{{marvelApiBaseUrl}}/movies

###
{{omdbApiBaseUrl}}/?s=love

###
{{swApiBaseUrl}}/people/1

###


https://swapi.dev/api/people/1

###

POST http://localhost:3005/api/auth/token HTTP/2
Content-Type: application/json

{
  "username": "tonystark",
  "password": "P3pp3RP0775"
}
